name: auto build engine

on: 
  release:
    types: [published]
  schedule:
    - cron: "0 16 * * *"
  push:
    branches: 
      - master
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install build depedencies
      run: |
        sudo apt update
        sudo apt install -y flex bison libelf-dev
        sudo apt remove clang-10 clang-11 clang-12 -y
        sudo apt autoremove -y
        sudo apt upgrade -y
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-13 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-13 100
        sudo apt upgrade -y
  
    - name: Bulid kernel
      run: |
        #git clone https://github.com/xanmod/linux.git -b 5.14-cacule --depth 1 linux   
        #git clone https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git -b for-kbuild-bot/current-stable --depth 1 linux      
        #git clone https://github.com/torvalds/linux.git --depth 1 linux 
        git clone https://github.com/nathanchance/WSL2-Linux-Kernel.git --depth 1 linux
        #git clone https://github.com/microsoft/WSL2-Linux-Kernel -b linux-msft-wsl-5.10.y --depth 1 linux
        #wget --no-check-certificate https://raw.githubusercontent.com/ShiShuMo/WSL2-Linux-Kernel-mss/master/0001-msft-wsl.patch
        pushd linux
        #git apply ../0001-msft-wsl.patch --reject
        #wget --no-check-certificate -O .config https://raw.githubusercontent.com/ShiShuMo/WSL2-Linux-Kernel-mss/master/config-wsl
        wget --no-check-certificate -O .config https://raw.githubusercontent.com/microsoft/WSL2-Linux-Kernel/linux-msft-wsl-5.10.y/Microsoft/config-wsl
        #scripts/config --disable PREEMPT_NONE
        #scripts/config --enable PREEMPT_RT
        make olddefconfig CC=clang HOSTCC=clang LOCALVERSION="-microsoft-ShiShuMo"
        make CC=clang HOSTCC=clang -j$(nproc) LOCALVERSION="-microsoft-ShiShuMo"
        popd

    - name: Upload kernel
      uses: actions/upload-artifact@master
      with:
        name: bzImage
        path: linux/arch/x86/boot/bzImage

  push:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Clean
      run: |
        rm bzImage
    
    - name: Download kernel
      uses: actions/download-artifact@master
      with:
        name: bzImage
        path: ./
    
    - name: Commit
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout --orphan new_branch
        git add -A
        git commit -am "update new file"
        git branch -D master
        git branch -m master
        git push origin master --force
